
services:
    symfony.cmf.navigation.hierarchyWalker:
        class: Symfony\CMF\Bundle\NavigationBundle\Service\HierarchyWalker
        arguments:
            jackalope: "@jackalope.loader"
            mapper: "@symfony.cmf.core.pathMapper"
        shared: true
